# Generated by Django 3.2.4 on 2021-06-29 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DumpTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.CharField(default='100', max_length=50, verbose_name='Бортовой номер')),
            ],
            options={
                'verbose_name': 'Самосвал',
                'verbose_name_plural': 'Самосвалы',
            },
        ),
        migrations.CreateModel(
            name='DumpTruckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Модель 1', max_length=250, verbose_name='Название модели')),
                ('tonnage', models.PositiveSmallIntegerField(default=100, verbose_name='Грузоподьёмность (т)')),
            ],
            options={
                'verbose_name': 'Модель самосвала',
                'verbose_name_plural': 'Модели самосвалов',
            },
        ),
        migrations.CreateModel(
            name='OreStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.PositiveSmallIntegerField(default=0, verbose_name='Загрузка (т)')),
                ('sio2_substance', models.PositiveSmallIntegerField(default=40, verbose_name='Cодержание кремния (%)')),
                ('fe_substance', models.PositiveSmallIntegerField(verbose_name='Cодержание железа (%)')),
                ('name', models.CharField(default='Склад 1', max_length=250, verbose_name='Название склада')),
                ('geometry', models.TextField(verbose_name='Геометрия склада в формате WKT')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='OreCargoTruckRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.PositiveSmallIntegerField(default=0, verbose_name='Загрузка (т)')),
                ('sio2_substance', models.PositiveSmallIntegerField(default=40, verbose_name='Cодержание кремния (%)')),
                ('fe_substance', models.PositiveSmallIntegerField(verbose_name='Cодержание железа (%)')),
                ('discharge_x', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Х координата разгрузки')),
                ('discharge_y', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Y координата разгрузки')),
                ('discharge_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время разгрузки')),
                ('target_storage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='front.orestorage', verbose_name='Целевой склад')),
                ('truck', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='front.dumptruck', verbose_name='Самосвал')),
            ],
            options={
                'verbose_name': 'Рейс с грузом руды',
                'verbose_name_plural': 'Рейсы с грузом руды',
            },
        ),
        migrations.AddField(
            model_name='dumptruck',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='front.dumptruckmodel'),
        ),
    ]
